/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 4;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int TIMES = 7;
  /** RegularExpression Id. */
  int DIV = 8;
  /** RegularExpression Id. */
  int LPAR = 9;
  /** RegularExpression Id. */
  int RPAR = 10;
  /** RegularExpression Id. */
  int EL = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int NEQ = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int NEG = 16;
  /** RegularExpression Id. */
  int GR = 17;
  /** RegularExpression Id. */
  int LR = 18;
  /** RegularExpression Id. */
  int GRE = 19;
  /** RegularExpression Id. */
  int LRE = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int LET = 23;
  /** RegularExpression Id. */
  int IN = 24;
  /** RegularExpression Id. */
  int IF = 25;
  /** RegularExpression Id. */
  int THEN = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int END = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int REF = 32;
  /** RegularExpression Id. */
  int REREF = 33;
  /** RegularExpression Id. */
  int DEREF = 34;
  /** RegularExpression Id. */
  int PRINT = 35;
  /** RegularExpression Id. */
  int PRINTLN = 36;
  /** RegularExpression Id. */
  int Id = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"true\"",
    "\"false\"",
    "\"let\"",
    "\"in\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"end\"",
    "\";\"",
    "\":=\"",
    "\"::=\"",
    "\"!\"",
    "\"print\"",
    "\"println\"",
    "<Id>",
  };

}
